"""tables

Revision ID: 4a803065cd9a
Revises: 
Create Date: 2024-01-26 17:44:34.021758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a803065cd9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Anime',
    sa.Column('Anime_ID', sa.Integer(), nullable=False),
    sa.Column('Anime_Name', sa.String(length=50), nullable=False),
    sa.Column('Anime_Genre', sa.String(length=25), nullable=False),
    sa.Column('Where_TW', sa.String(length=25), nullable=True),
    sa.Column('Anime_Script', sa.String(length=1000), nullable=True),
    sa.Column('Anime_Image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Anime_ID'),
    sa.UniqueConstraint('Anime_ID'),
    sa.UniqueConstraint('Anime_Image'),
    sa.UniqueConstraint('Anime_Name')
    )
    op.create_table('Books',
    sa.Column('Book_ID', sa.Integer(), nullable=False),
    sa.Column('Book_Name', sa.String(length=100), nullable=False),
    sa.Column('Book_Author', sa.String(length=30), nullable=False),
    sa.Column('Book_Genre', sa.String(length=25), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('Book_Script', sa.String(length=1000), nullable=True),
    sa.Column('Book_Image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Book_ID'),
    sa.UniqueConstraint('Book_ID'),
    sa.UniqueConstraint('Book_Image'),
    sa.UniqueConstraint('Book_Name')
    )
    op.create_table('Games',
    sa.Column('Game_ID', sa.Integer(), nullable=False),
    sa.Column('Game_Name', sa.String(length=50), nullable=False),
    sa.Column('Game_Genre', sa.String(length=30), nullable=False),
    sa.Column('W_Console', sa.String(length=100), nullable=True),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('Game_Script', sa.String(length=1000), nullable=True),
    sa.Column('Game_Image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Game_ID'),
    sa.UniqueConstraint('Game_ID'),
    sa.UniqueConstraint('Game_Image'),
    sa.UniqueConstraint('Game_Name')
    )
    op.create_table('message_board',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('post_category', sa.String(length=50), nullable=False),
    sa.Column('post_author', sa.String(length=30), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('user_accounts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_profiles',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('user_accounts')
    op.drop_table('message_board')
    op.drop_table('Games')
    op.drop_table('Books')
    op.drop_table('Anime')
    # ### end Alembic commands ###
