"""Test update

Revision ID: a7a4d216a7b9
Revises: 
Create Date: 2024-01-26 16:40:27.000837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7a4d216a7b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('Game_ID')
        batch_op.drop_index('Game_Name')

    op.drop_table('games')
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.drop_index('Anime_ID')
        batch_op.drop_index('Anime_Name')

    op.drop_table('anime')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('user_profiles')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('Book_ID')
        batch_op.drop_index('Book_Name')

    op.drop_table('books')
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.drop_index('user_id')
        batch_op.drop_index('username')

    op.drop_table('user_accounts')
    with op.batch_alter_table('message_board', schema=None) as batch_op:
        batch_op.drop_index('post_id')

    op.drop_table('message_board')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_board',
    sa.Column('post_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_content', mysql.TEXT(), nullable=False),
    sa.Column('post_category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('post_author', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('post_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('post_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('message_board', schema=None) as batch_op:
        batch_op.create_index('post_id', ['post_id'], unique=True)

    op.create_table('user_accounts',
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('user_id', ['user_id'], unique=True)

    op.create_table('books',
    sa.Column('Book_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Book_Name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Book_Author', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('Book_Genre', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('Price', mysql.FLOAT(), nullable=False),
    sa.Column('Book_Script', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('Book_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('Book_Name', ['Book_Name'], unique=True)
        batch_op.create_index('Book_ID', ['Book_ID'], unique=True)

    op.create_table('user_profiles',
    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=254), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('interests', mysql.TEXT(), nullable=True),
    sa.Column('date_joined', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('anime',
    sa.Column('Anime_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Anime_Name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Anime_Genre', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('Where_TW', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('Anime_Script', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('Anime_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.create_index('Anime_Name', ['Anime_Name'], unique=True)
        batch_op.create_index('Anime_ID', ['Anime_ID'], unique=True)

    op.create_table('games',
    sa.Column('Game_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Game_Name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Game_Genre', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('W_Console', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Price', mysql.FLOAT(), nullable=False),
    sa.Column('Game_Script', mysql.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('Game_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index('Game_Name', ['Game_Name'], unique=True)
        batch_op.create_index('Game_ID', ['Game_ID'], unique=True)

    # ### end Alembic commands ###
